// <auto-generated />
using System;
using Ezac.Roster.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ezac.Roster.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240508070242_dataseeding")]
    partial class dataseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.ApplicationCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Calendars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 11, 8, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2953),
                            Name = "Zweefvliegkalender",
                            Start = new DateTime(2024, 5, 8, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54e23e5f-c2d2-4bb5-82fa-176a7db9972f"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 8, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8146a091-1fc3-4d87-90d7-43b97151e834"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 9, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Thursday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("736d1928-a0e7-4c1c-b4de-a2be70408178"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 10, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Friday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b1616c2e-e72a-4ca8-a133-3c9175692361"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 11, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Saturday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e071a88e-b79e-4c1a-ad59-b2dde43204a5"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 12, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Sunday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f9d2b92b-6caa-4c0f-992e-f5d9fe2afc80"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 13, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Monday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d7f935c4-278b-4f95-b802-73543433f659"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 14, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2d5eef61-d6a9-46de-ad55-673d60917113"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 15, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c7290798-7d9f-494d-8ddc-c3efc0c79d04"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 16, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Thursday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00bbbd24-b99b-4f14-8ff2-75d8a5d9c801"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 17, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Friday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("36d780c1-959f-4480-8698-ea91e273065b"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 18, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Saturday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b9aab22c-e2ff-47f7-8860-c44466757053"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 19, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Sunday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b8cefcd3-99e0-4849-8062-48f891f99fb2"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 20, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Monday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d4de14da-e0eb-4188-b942-305f988c29b7"),
                            CalendarId = new Guid("414a1234-e5cb-4ddc-b821-7393557ed8c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 21, 9, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("DayPeriods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e2a2415-5f77-4783-8b42-6ec477f99248"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("54e23e5f-c2d2-4bb5-82fa-176a7db9972f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 8, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 8, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c85a0404-1649-40e1-ba94-dc36a7f9d184"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("54e23e5f-c2d2-4bb5-82fa-176a7db9972f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 9, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 8, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0d208ce8-78b2-4a32-be7e-f42381172753"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("54e23e5f-c2d2-4bb5-82fa-176a7db9972f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 9, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 9, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6e42af9b-f4a8-4500-bb12-4c31b3f63195"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("8146a091-1fc3-4d87-90d7-43b97151e834"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 9, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 9, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a6700cb7-a340-4e19-887f-db5ac7eaf375"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("8146a091-1fc3-4d87-90d7-43b97151e834"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 10, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 9, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("55b2beeb-2871-457c-94e3-87ad44084bc6"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("8146a091-1fc3-4d87-90d7-43b97151e834"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 10, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 10, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a73e7c3e-cfca-4278-a0ea-5302d37abe43"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("736d1928-a0e7-4c1c-b4de-a2be70408178"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 10, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 10, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("70eee5a3-e22c-4718-b4ed-93b28030b465"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("736d1928-a0e7-4c1c-b4de-a2be70408178"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 11, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 10, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2ded5841-8211-4229-b864-ad36be89ddd6"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("736d1928-a0e7-4c1c-b4de-a2be70408178"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 11, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 11, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7fe2f2e8-96cb-4d98-929c-111512e15183"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b1616c2e-e72a-4ca8-a133-3c9175692361"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 11, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 11, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6b9d8421-e272-42bf-8cad-cd0ea01700d1"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b1616c2e-e72a-4ca8-a133-3c9175692361"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 12, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 11, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("78df6c1f-ef7b-4065-8057-ff42aa65ac09"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b1616c2e-e72a-4ca8-a133-3c9175692361"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 12, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 12, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6e49759b-3019-4b0c-a511-4cfd7a974f0b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e071a88e-b79e-4c1a-ad59-b2dde43204a5"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 12, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 12, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("09980fa3-9b8e-4a7f-a2fb-d116dab4c5da"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e071a88e-b79e-4c1a-ad59-b2dde43204a5"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 13, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 12, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ac9394d2-0bfa-42fe-a021-9ccdf7c63d19"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e071a88e-b79e-4c1a-ad59-b2dde43204a5"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 13, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 13, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d8fc8c57-fa1b-43aa-93e9-d49947009ebd"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("f9d2b92b-6caa-4c0f-992e-f5d9fe2afc80"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 13, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 13, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c76845a1-4ab1-4864-a693-9c9a42cbb12a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("f9d2b92b-6caa-4c0f-992e-f5d9fe2afc80"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 14, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 13, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ad9223b4-bc9e-422e-ab7f-c8508f1eff4b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("f9d2b92b-6caa-4c0f-992e-f5d9fe2afc80"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 14, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 14, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4c20f89c-cbea-4433-933e-bf39496801fc"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d7f935c4-278b-4f95-b802-73543433f659"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 14, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 14, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1154025b-deae-4235-87e6-903d74dac087"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d7f935c4-278b-4f95-b802-73543433f659"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 15, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 14, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f39b38b9-d732-44e8-a0a2-9ab0fae77000"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d7f935c4-278b-4f95-b802-73543433f659"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 15, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 15, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("04a3c594-797c-4225-a0c0-79ea404025da"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("2d5eef61-d6a9-46de-ad55-673d60917113"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 15, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 15, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fc5b1fd2-1a5f-4736-8fed-a02948efe102"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("2d5eef61-d6a9-46de-ad55-673d60917113"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 16, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 15, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2687c773-6e67-41ba-a412-1e649c19e71c"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("2d5eef61-d6a9-46de-ad55-673d60917113"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 16, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 16, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("83a00c23-aa2c-4493-a275-4e89ed37e063"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c7290798-7d9f-494d-8ddc-c3efc0c79d04"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 16, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 16, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bc01372b-d851-4bd1-a72c-d51f447d35a3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c7290798-7d9f-494d-8ddc-c3efc0c79d04"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 17, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 16, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2285474e-015d-46fb-aa5e-a5c16e786aa3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c7290798-7d9f-494d-8ddc-c3efc0c79d04"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 17, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 17, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8d0b2bbd-61d9-491a-a9ab-3378a036488f"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("00bbbd24-b99b-4f14-8ff2-75d8a5d9c801"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 17, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 17, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("85c79c34-0090-45c7-a50c-f6bbcd79a188"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("00bbbd24-b99b-4f14-8ff2-75d8a5d9c801"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 18, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 17, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2264e7cf-1ccc-4035-9a2e-6e1207ef6e9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("00bbbd24-b99b-4f14-8ff2-75d8a5d9c801"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 18, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 18, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bc0c105a-1627-4292-84f6-f76b64038ddb"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("36d780c1-959f-4480-8698-ea91e273065b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 18, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 18, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("92554e8a-074b-41a3-822e-15daa01f2270"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("36d780c1-959f-4480-8698-ea91e273065b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 19, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 18, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ef9532c6-e301-4ee2-ad07-5a80b3894346"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("36d780c1-959f-4480-8698-ea91e273065b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 19, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 19, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bccefd26-9e26-4ac4-aa31-34ff2a5361e0"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b9aab22c-e2ff-47f7-8860-c44466757053"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 19, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 19, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("25255ead-bf89-4e82-92ad-a63ae515d71e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b9aab22c-e2ff-47f7-8860-c44466757053"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 20, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 19, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e446ed35-0512-457e-add6-ea0c21f31a6d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b9aab22c-e2ff-47f7-8860-c44466757053"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 20, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 20, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("eed31ac7-d56c-49c9-9668-066c059655ab"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b8cefcd3-99e0-4849-8062-48f891f99fb2"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 20, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 20, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7620dcc3-dc15-4884-9fac-5ca9d57d8be6"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b8cefcd3-99e0-4849-8062-48f891f99fb2"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 21, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 20, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ae261741-e74a-4624-baaf-074734ed182c"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b8cefcd3-99e0-4849-8062-48f891f99fb2"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 21, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 21, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4873e4d8-74f3-437e-b6fe-41e24cffbbec"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d4de14da-e0eb-4188-b942-305f988c29b7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 21, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 21, 17, 32, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e7036b35-f07f-4e64-8f86-8392be3e4f4c"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d4de14da-e0eb-4188-b942-305f988c29b7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 22, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 21, 22, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cf33b3c8-6b09-4856-be2d-92e29d991b63"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d4de14da-e0eb-4188-b942-305f988c29b7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 22, 8, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 22, 2, 2, 42, 216, DateTimeKind.Local).AddTicks(2913),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DayPeriodId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lierist",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Startofficier",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bardienst",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Instructeur",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Preference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("DayPeriodId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Preference");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Scaling")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnny@ezac.com",
                            IsAdmin = false,
                            Name = "Johnny Debeer",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alfie@ezac.com",
                            IsAdmin = false,
                            Name = "Alfonso Rosseel",
                            Scaling = 0.5,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Admin@ezac.com",
                            IsAdmin = true,
                            Name = "Mohammed Ali",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PermissionUser", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("PermissionUser");

                    b.HasData(
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000003"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000004"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000003"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000004"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000007")
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.ApplicationCalendar", "Calendar")
                        .WithMany("Days")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Day", "Day")
                        .WithMany("DayPeriods")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.DayPeriod", "DayPeriod")
                        .WithMany("Jobs")
                        .HasForeignKey("DayPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.Permission", "Permission")
                        .WithMany("Jobs")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayPeriod");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Preference", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Day", "Day")
                        .WithMany("Preferences")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.DayPeriod", "DayPeriod")
                        .WithMany("Preferences")
                        .HasForeignKey("DayPeriodId");

                    b.HasOne("Ezac.Roster.Domain.Entities.Job", "Job")
                        .WithMany("Preferences")
                        .HasForeignKey("JobId");

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("DayPeriod");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermissionUser", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.ApplicationCalendar", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.Navigation("DayPeriods");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Permission", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
