// <auto-generated />
using System;
using Ezac.Roster.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ezac.Roster.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240523111147_update-user-calendar-realation")]
    partial class updateusercalendarrealation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.ApplicationCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Calendars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 11, 23, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2918),
                            Name = "Zweefvliegkalender",
                            Start = new DateTime(2024, 5, 23, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d345137d-d589-4343-81d1-4fe259cfbb48"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 22, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7a5554f3-7e11-4af1-8713-c69587da481a"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 23, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Thursday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ecdec4ec-d7b1-45ba-ac79-37965b4d2e01"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 24, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Friday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5531b5bb-0284-49ca-8a1e-88da8a894ba9"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 25, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Saturday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4e802fe9-e8d9-464b-8aa5-47b257cfa827"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 26, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Sunday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bc65a03c-49c1-453d-84c4-fccb07031e39"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 27, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Monday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7640c9ac-6636-44da-b6b6-19dc048789e4"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 28, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dd8b2178-b280-4cb5-a850-7056e5a2b471"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 29, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("74390deb-9c73-4acb-9744-a4f9dad7c0f0"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 30, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Thursday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0b3708ab-b9ec-4b5e-90f5-f00defad2f84"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 31, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Friday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ef3cf44b-0028-4187-920c-98f141378ea5"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 1, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Saturday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8e130ebf-489d-4aca-bc8f-37796837f32c"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 2, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Sunday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("266c22aa-e0a7-4cbf-b03e-b7fd7e14043a"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 3, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Monday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("571c7c86-e9ce-459a-986e-4999a2462555"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 4, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f6792bbf-30e0-4294-af7a-25fab9c6a029"),
                            CalendarId = new Guid("181e6f2d-18f0-4900-b7bb-f11ad35617ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 5, 13, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("DayPeriods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b190fb5-2c61-41ff-97ea-7a1fbc8544e3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d345137d-d589-4343-81d1-4fe259cfbb48"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 23, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 22, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e6eb0eca-d46b-449a-8fdb-2dcda57e65bb"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d345137d-d589-4343-81d1-4fe259cfbb48"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 23, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 23, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("79b09b7c-3ef6-4cca-8a50-c7a114108893"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d345137d-d589-4343-81d1-4fe259cfbb48"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 23, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 23, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("abf8c186-e174-4fc8-b88a-9088a4ccf8d1"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7a5554f3-7e11-4af1-8713-c69587da481a"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 24, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 23, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1a05fdc5-d05b-4a8a-b070-8978b369d560"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7a5554f3-7e11-4af1-8713-c69587da481a"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 24, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 24, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f23caaf8-b209-4e1e-a93f-9e1eb4c2f095"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7a5554f3-7e11-4af1-8713-c69587da481a"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 24, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 24, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ee0d238b-e18a-47e8-b330-bfa85b70ccef"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("ecdec4ec-d7b1-45ba-ac79-37965b4d2e01"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 25, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 24, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f16ceb9b-db63-4356-92bd-4a9c06b8e6f1"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("ecdec4ec-d7b1-45ba-ac79-37965b4d2e01"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 25, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 25, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5e63e4de-d66e-4806-8722-22b3fc1c4ebc"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("ecdec4ec-d7b1-45ba-ac79-37965b4d2e01"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 25, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 25, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("75540484-c1e4-4734-86fe-387ef3d9f5a3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5531b5bb-0284-49ca-8a1e-88da8a894ba9"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 26, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 25, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e32517de-4ba0-4e98-bcea-c1a486b80f71"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5531b5bb-0284-49ca-8a1e-88da8a894ba9"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 26, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 26, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("95ccae5b-a06a-4d84-abfc-c08349188bae"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5531b5bb-0284-49ca-8a1e-88da8a894ba9"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 26, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 26, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a1426b68-e6ac-46ba-a833-a166ceb372ea"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("4e802fe9-e8d9-464b-8aa5-47b257cfa827"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 27, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 26, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("31f7c2ec-ce15-48a7-99c7-ad04baa06935"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("4e802fe9-e8d9-464b-8aa5-47b257cfa827"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 27, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 27, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2b6b58eb-870f-450b-a384-808e3a587c84"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("4e802fe9-e8d9-464b-8aa5-47b257cfa827"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 27, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 27, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("eef6486c-4444-465c-b464-b9eabb1b4f88"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("bc65a03c-49c1-453d-84c4-fccb07031e39"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 28, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 27, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a95b0b50-cce4-4cc1-865c-35a0e96d3922"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("bc65a03c-49c1-453d-84c4-fccb07031e39"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 28, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 28, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0364880a-f2c9-4bb2-afc5-ec3a27b039a9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("bc65a03c-49c1-453d-84c4-fccb07031e39"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 28, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 28, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7de0aefe-958f-4558-b99d-d561a46f70c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7640c9ac-6636-44da-b6b6-19dc048789e4"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 29, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 28, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("778c7041-f529-49f4-8fbf-6c43a7d0ee6f"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7640c9ac-6636-44da-b6b6-19dc048789e4"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 29, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 29, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e68dfeac-c19f-4759-9d8d-a8cceb5ae4a8"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7640c9ac-6636-44da-b6b6-19dc048789e4"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 29, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 29, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f256b613-6f19-4167-9a98-801edefe397f"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("dd8b2178-b280-4cb5-a850-7056e5a2b471"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 30, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 29, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c516b679-17bc-43be-8212-d5e7e2bbafaf"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("dd8b2178-b280-4cb5-a850-7056e5a2b471"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 30, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 30, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("17c8a081-6738-43ef-bf2e-4bac29250115"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("dd8b2178-b280-4cb5-a850-7056e5a2b471"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 30, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 30, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9eea9ab6-faa8-40e2-b350-f28f69d37aa1"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("74390deb-9c73-4acb-9744-a4f9dad7c0f0"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 31, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 30, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cefab9d1-09c2-4292-9bb8-921d295a9252"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("74390deb-9c73-4acb-9744-a4f9dad7c0f0"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 31, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 31, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4f5eaa65-5dd9-4184-956b-60de64bcacd9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("74390deb-9c73-4acb-9744-a4f9dad7c0f0"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 31, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 31, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a8604965-4cad-4874-8763-d6fc5a605e27"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("0b3708ab-b9ec-4b5e-90f5-f00defad2f84"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 1, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 31, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c44263fb-1e9b-4b62-8d61-a900f543dfbe"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("0b3708ab-b9ec-4b5e-90f5-f00defad2f84"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 1, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 1, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1d475074-d5bb-4567-84ab-648feaa8d578"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("0b3708ab-b9ec-4b5e-90f5-f00defad2f84"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 1, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 1, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("809b67ee-ebf7-4c7a-b3a3-ffe4cad09b6b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("ef3cf44b-0028-4187-920c-98f141378ea5"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 2, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 1, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("58901b21-9044-48bb-81b0-9b3558deb946"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("ef3cf44b-0028-4187-920c-98f141378ea5"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 2, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 2, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e2e1e53a-a240-484d-bdfa-be73129efa6d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("ef3cf44b-0028-4187-920c-98f141378ea5"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 2, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 2, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7b3f060a-4041-4e4d-9cbc-da47ec21d4ad"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("8e130ebf-489d-4aca-bc8f-37796837f32c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 3, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 2, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ee8d46d2-dfb0-49de-9106-c19b94ba5fa9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("8e130ebf-489d-4aca-bc8f-37796837f32c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 3, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 3, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bf599969-290d-417a-ade5-ea01541bd208"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("8e130ebf-489d-4aca-bc8f-37796837f32c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 3, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 3, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("af03745a-4acc-42c4-806f-018699ead65f"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("266c22aa-e0a7-4cbf-b03e-b7fd7e14043a"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 4, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 3, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("eb091ebc-3ed9-47f7-a078-7ea9e0825be2"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("266c22aa-e0a7-4cbf-b03e-b7fd7e14043a"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 4, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 4, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ac7b5293-591f-447d-b8f7-da9a61ab63fa"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("266c22aa-e0a7-4cbf-b03e-b7fd7e14043a"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 4, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 4, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4134c504-27ec-45dd-b4ce-740558801559"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("571c7c86-e9ce-459a-986e-4999a2462555"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 5, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 4, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("744dbfdd-d650-43ad-8223-a4f96f081b2a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("571c7c86-e9ce-459a-986e-4999a2462555"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 5, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 5, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d22c1fb7-e767-4593-b28e-6582acf89ff8"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("571c7c86-e9ce-459a-986e-4999a2462555"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 5, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 5, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("860fdc12-5190-4c8f-9808-cc67e4d4a6e9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("f6792bbf-30e0-4294-af7a-25fab9c6a029"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 6, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 5, 21, 41, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6dc13acb-d224-4896-ba1c-4056a1ceeee7"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("f6792bbf-30e0-4294-af7a-25fab9c6a029"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 6, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 6, 2, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8a0e9245-2476-40b8-bdc3-bde7952c1e4a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("f6792bbf-30e0-4294-af7a-25fab9c6a029"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 6, 12, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 6, 6, 11, 47, 112, DateTimeKind.Local).AddTicks(2875),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DayPeriodId");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lierist",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Startofficier",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bardienst",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Instructeur",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Preference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("DayPeriodId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Preference");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationCalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalId")
                        .HasColumnType("int");

                    b.Property<double>("Scaling")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationCalendarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnny@ezac.com",
                            Name = "Johnny Debeer",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alfie@ezac.com",
                            Name = "Alfonso Rosseel",
                            OriginalId = 0,
                            Scaling = 0.5,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Admin@ezac.com",
                            Name = "Mohammed Ali",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Diego@ezac.com",
                            Name = "Diego Maradonna",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mitch@ezac.com",
                            Name = "Mitch Mitchell",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mileto@ezac.com",
                            Name = "Mileto Di Marco",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Antoinne@ezac.com",
                            Name = "Antoinne De Vlieger",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Siegfried@ezac.com",
                            Name = "Siegfried Dedeyne",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dries@ezac.com",
                            Name = "Dries Deboosere",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9f425ae-d712-4cb2-9d69-bd5da087f174"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 1,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("60e2ad9f-44cd-41e5-9c9e-cbe8ec3537e2"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 5,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("13ef4064-620d-4030-b5a0-1e0637eb13e5"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("c747f09c-f50f-4e0a-9fea-76ccd7a89e3b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 6,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("20cb8a92-aab1-4720-9070-481acf01ba9b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 8,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("a0d81f3f-c9e9-43ef-8f52-3cf9cc2bf207"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 2,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("a8a7adae-b404-4334-8aac-49f3a0e866ba"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 1,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("f0b785e6-b389-440e-bda6-1e8ecd6d0cde"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 9,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("cb0ea815-f4c4-45ae-b09b-6b811cff494a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 7,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("c1c99fe5-b7cd-43b0-9631-fca7309f921d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("a308a0fe-cca1-4fe7-b079-6d6c7ade7a54"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 3,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("b8e12b0e-0d75-4864-b87c-c1aff7239e07"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 1,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("f34fe1d2-003c-4870-a2c9-07b20006f499"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 5,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("4bedf104-6e3e-42ff-ad25-69a65abf542d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("b26945ee-e428-4456-b17c-f54b6ecd274e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 7,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("3a936098-db99-49d5-9aac-0b7e020fe9ff"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 2,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("b56a1092-7727-4784-8239-85297f53797d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 3,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("012f52e9-5bfd-4d8d-adcf-c65f137f6ea9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 8,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("9783ec6b-eddc-4e1d-a784-6d3d0105382e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 9,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("349abb5a-a87e-46e8-a540-2f2c33f063cf"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("775390ce-73e2-4128-b1a7-42d8c5040cdf"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 2,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("137af9ee-5faf-4e75-9b26-e753fa658176"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 8,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000013")
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.ApplicationCalendar", "Calendar")
                        .WithMany("Days")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Day", "Day")
                        .WithMany("DayPeriods")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.DayPeriod", "DayPeriod")
                        .WithMany("Jobs")
                        .HasForeignKey("DayPeriodId");

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId");

                    b.Navigation("DayPeriod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Preference", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Day", "Day")
                        .WithMany("Preferences")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.DayPeriod", "DayPeriod")
                        .WithMany("Preferences")
                        .HasForeignKey("DayPeriodId");

                    b.HasOne("Ezac.Roster.Domain.Entities.Job", "Job")
                        .WithMany("Preferences")
                        .HasForeignKey("JobId");

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("DayPeriod");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.ApplicationCalendar", "ApplicationCalendar")
                        .WithMany("Users")
                        .HasForeignKey("ApplicationCalendarId");

                    b.Navigation("ApplicationCalendar");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.ApplicationCalendar", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.Navigation("DayPeriods");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Preferences");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
