// <auto-generated />
using System;
using Ezac.Roster.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ezac.Roster.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240523085745_adjust-user-entity")]
    partial class adjustuserentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCalendarUser", b =>
                {
                    b.Property<Guid>("ApplicationCalendarsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationCalendarsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ApplicationCalendarUser");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.ApplicationCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Calendars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 11, 23, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1716),
                            Name = "Zweefvliegkalender",
                            Start = new DateTime(2024, 5, 23, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a63b13d-34a4-44ba-8daf-1b03550027ae"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 22, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b8a5f2ec-542e-4e07-9bcc-8e815f2abb8b"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 23, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Thursday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c42c7c2e-5476-4af9-be3f-4609a7635888"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 24, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Friday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c38c4f7d-f0ab-4339-8c59-c58246eade24"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 25, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Saturday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("998d9836-8dc7-489e-bbcb-29e85a559037"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 26, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Sunday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ce7efe55-988a-442d-957b-65a307158336"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 27, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Monday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4b958f0e-deea-4f70-8ff2-fa6cbe9d46c7"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 28, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("92f31960-fde6-4fc4-abe6-9d29a99a4b43"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 29, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("844fde77-902a-4975-93f8-119b2a8416f2"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 30, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Thursday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7ee19617-d865-4db7-84b0-4f31be598e2f"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 31, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Friday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("758ba8d0-c43f-4d36-baac-c342f733e5af"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 1, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Saturday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("97ae2d84-1af4-4868-be59-02cb4ac4e0a8"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 2, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Sunday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5efa091c-1ed1-4ce1-98ee-18cb049a210e"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 3, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Monday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("78db8a6c-bffe-4998-b214-97cc5daed0a3"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 4, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0fce4dda-d5fd-4e7e-9064-d350fd62d7f7"),
                            CalendarId = new Guid("c2b7745e-1099-458e-bb10-06b1f8370a15"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 5, 10, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("DayPeriods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77198afe-d9e6-40a7-be47-39362649b1b6"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("1a63b13d-34a4-44ba-8daf-1b03550027ae"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 22, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 22, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f792f75b-075e-4efb-9916-9d7cdc34bb6d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("1a63b13d-34a4-44ba-8daf-1b03550027ae"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 23, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 22, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("369660d0-aac9-4d27-97e9-adef4c7b2f41"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("1a63b13d-34a4-44ba-8daf-1b03550027ae"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 23, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 23, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f7ea5210-95a5-4e79-a411-12db7354dfb0"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b8a5f2ec-542e-4e07-9bcc-8e815f2abb8b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 23, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 23, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("528a4866-fc81-4f11-ab47-14fec148af7a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b8a5f2ec-542e-4e07-9bcc-8e815f2abb8b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 24, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 23, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7ae75f8c-ed23-48a8-8385-4c43489b93cc"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("b8a5f2ec-542e-4e07-9bcc-8e815f2abb8b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 24, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 24, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f5fd82ba-2418-446b-b18c-2cade53c64d5"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c42c7c2e-5476-4af9-be3f-4609a7635888"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 24, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 24, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("583d58a9-0c92-42ba-bb8a-7aacbff659c6"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c42c7c2e-5476-4af9-be3f-4609a7635888"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 25, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 24, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0eb236e1-201a-4bd6-9cdf-c1f2ccad00d9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c42c7c2e-5476-4af9-be3f-4609a7635888"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 25, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 25, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9c148b90-cd15-4a9d-954b-aafa91b8ca9d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c38c4f7d-f0ab-4339-8c59-c58246eade24"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 25, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 25, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("75d45b33-7262-46df-88b8-612af09fd713"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c38c4f7d-f0ab-4339-8c59-c58246eade24"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 26, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 25, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("49947264-bc81-4219-a46a-6f6299ba982e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c38c4f7d-f0ab-4339-8c59-c58246eade24"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 26, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 26, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0e0ffd57-ed4d-4244-a8d5-72aed37e6fee"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("998d9836-8dc7-489e-bbcb-29e85a559037"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 26, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 26, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f9fdd21a-7158-4af6-b558-b7cb89683ee0"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("998d9836-8dc7-489e-bbcb-29e85a559037"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 27, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 26, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("08c5c289-9057-4f2a-a611-f080938149d4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("998d9836-8dc7-489e-bbcb-29e85a559037"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 27, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 27, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("811e5b47-3d2b-472b-a619-87655e59d5d8"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("ce7efe55-988a-442d-957b-65a307158336"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 27, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 27, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e05366a0-f870-4a11-8716-c6e0961d9bec"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("ce7efe55-988a-442d-957b-65a307158336"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 28, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 27, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a396d09f-2e96-4103-b8e3-e2b57046a061"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("ce7efe55-988a-442d-957b-65a307158336"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 28, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 28, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b2372e1c-9de7-48d9-966d-63dd8d0dc567"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("4b958f0e-deea-4f70-8ff2-fa6cbe9d46c7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 28, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 28, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c686df53-0c85-406d-9563-7b9bdf8cc644"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("4b958f0e-deea-4f70-8ff2-fa6cbe9d46c7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 29, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 28, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1d61629d-c458-4db4-ab07-e1d41843f81c"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("4b958f0e-deea-4f70-8ff2-fa6cbe9d46c7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 29, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 29, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6ea63300-1cb5-42dc-b25b-6a1e44c4e868"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("92f31960-fde6-4fc4-abe6-9d29a99a4b43"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 29, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 29, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7715d401-f348-4405-809f-1e9415c0e632"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("92f31960-fde6-4fc4-abe6-9d29a99a4b43"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 30, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 29, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1fb2db9-1874-4139-bc49-850fce66baf6"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("92f31960-fde6-4fc4-abe6-9d29a99a4b43"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 30, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 30, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ef09e0f8-3272-48b5-a357-29ea03416d8c"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("844fde77-902a-4975-93f8-119b2a8416f2"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 30, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 30, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9a2fa4ef-38d0-401e-8697-3026e50d2aa3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("844fde77-902a-4975-93f8-119b2a8416f2"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 31, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 30, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fb82a5b6-629c-4b8c-870b-ad1950a9614f"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("844fde77-902a-4975-93f8-119b2a8416f2"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 31, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 31, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("75683a0c-67ce-4626-b6de-57316de7a6fb"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7ee19617-d865-4db7-84b0-4f31be598e2f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 31, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 31, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("300e13e8-edd1-4551-ac33-79920fd511ad"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7ee19617-d865-4db7-84b0-4f31be598e2f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 1, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 31, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6eb7e8f9-856e-4f2a-bb89-5357279a58f6"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7ee19617-d865-4db7-84b0-4f31be598e2f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 1, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 1, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("448cf5d3-d9cb-400a-be51-3f81b8ae011e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("758ba8d0-c43f-4d36-baac-c342f733e5af"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 1, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 1, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3f7f25f8-e72a-4c90-a9d0-d9ab7a773bcb"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("758ba8d0-c43f-4d36-baac-c342f733e5af"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 2, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 1, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d00c5fab-1d43-4c25-974c-28fd0f8e6245"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("758ba8d0-c43f-4d36-baac-c342f733e5af"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 2, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 2, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("86290f28-e939-49a6-a587-5ae1cc06db29"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("97ae2d84-1af4-4868-be59-02cb4ac4e0a8"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 2, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 2, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1352eb2-715a-4dd5-9224-e2562023e614"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("97ae2d84-1af4-4868-be59-02cb4ac4e0a8"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 3, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 2, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2d8c1a47-1386-479e-8903-dd4a41ca27ef"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("97ae2d84-1af4-4868-be59-02cb4ac4e0a8"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 3, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 3, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8f481e32-3dc4-4438-9c8f-630f819c966a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5efa091c-1ed1-4ce1-98ee-18cb049a210e"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 3, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 3, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("979be1ad-9dca-43e0-980a-0d897d53d032"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5efa091c-1ed1-4ce1-98ee-18cb049a210e"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 4, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 3, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("245fb1b9-130f-4017-afc0-2ec1b2f36401"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5efa091c-1ed1-4ce1-98ee-18cb049a210e"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 4, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 4, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3013083d-cc6d-4788-a1b5-2537483aedc4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("78db8a6c-bffe-4998-b214-97cc5daed0a3"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 4, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 4, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("721f8e36-6f53-40c4-a73c-c5b56f239a99"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("78db8a6c-bffe-4998-b214-97cc5daed0a3"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 5, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 4, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22efb63e-b894-47be-81f7-2a4b8de45986"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("78db8a6c-bffe-4998-b214-97cc5daed0a3"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 5, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 5, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ad5dc8fc-0e14-49a2-b6d9-053a7986643e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("0fce4dda-d5fd-4e7e-9064-d350fd62d7f7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 5, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 5, 19, 27, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5848dec4-87ed-403a-adb8-2928f3a4ed25"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("0fce4dda-d5fd-4e7e-9064-d350fd62d7f7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 6, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 5, 23, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("10da7ff0-85cb-476d-a8ba-195ac5dd865a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("0fce4dda-d5fd-4e7e-9064-d350fd62d7f7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 6, 9, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 6, 3, 57, 44, 71, DateTimeKind.Local).AddTicks(1672),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DayPeriodId");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lierist",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Startofficier",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bardienst",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Instructeur",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Preference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("DayPeriodId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Preference");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalId")
                        .HasColumnType("int");

                    b.Property<double>("Scaling")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnny@ezac.com",
                            Name = "Johnny Debeer",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alfie@ezac.com",
                            Name = "Alfonso Rosseel",
                            OriginalId = 0,
                            Scaling = 0.5,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Admin@ezac.com",
                            Name = "Mohammed Ali",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Diego@ezac.com",
                            Name = "Diego Maradonna",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mitch@ezac.com",
                            Name = "Mitch Mitchell",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mileto@ezac.com",
                            Name = "Mileto Di Marco",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Antoinne@ezac.com",
                            Name = "Antoinne De Vlieger",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Siegfried@ezac.com",
                            Name = "Siegfried Dedeyne",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dries@ezac.com",
                            Name = "Dries Deboosere",
                            OriginalId = 0,
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9271fd45-71b6-4391-84cd-5ec5a72ae15d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 1,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("086e6712-6aed-4750-ab8c-01a9ee182a2d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 5,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("be021784-a4b4-46e9-ba81-f272884b4bc9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("d2590645-3d5d-4fda-adee-ccf1ed6d8f67"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 6,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("08742d6d-92a0-43a1-9cc3-2eea0692986b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 8,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("59ae60d3-19af-4c36-a7b5-3ee4802795d1"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 2,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b3c96cc5-8a2a-4cb2-9310-4b0486d35b82"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 1,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("beb84793-9b77-4d99-8ac2-36005021e28a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 9,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("b539c859-3520-40e6-bf21-477e632e982f"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 7,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("78cb03de-2ae2-49d8-9df7-fd9e01cf4302"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("eea86202-52cf-4151-baef-32576c97e2b5"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 3,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("79e5fc4f-5cf3-45b5-b3f5-5e8f052b32d1"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 1,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("f80eac43-92f2-4c72-bdc6-dd655f188cd0"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 5,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("338cbe03-1a73-4602-ae5d-d971f6963562"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("5560051c-f5f3-4aa5-8c8f-0aafbbb67f96"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 7,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("289d836f-c795-4ad7-99c9-e2680bb997d1"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 2,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("86da7d1a-9a21-4ffb-a01d-dca37acb8f93"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 3,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("ef63a6da-8249-442c-89c4-1086c3682afc"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 8,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("fcfae561-2759-4448-87f6-09554f98b960"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 9,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("3c17d171-8e3b-4d62-867f-60dc804b0026"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("c1479a72-3dc2-4ebb-a109-f1ba46c7a922"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 2,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("05c2b782-459a-4586-9e96-89bb06c49b3d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 8,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000013")
                        });
                });

            modelBuilder.Entity("ApplicationCalendarUser", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.ApplicationCalendar", null)
                        .WithMany()
                        .HasForeignKey("ApplicationCalendarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.ApplicationCalendar", "Calendar")
                        .WithMany("Days")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Day", "Day")
                        .WithMany("DayPeriods")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.DayPeriod", "DayPeriod")
                        .WithMany("Jobs")
                        .HasForeignKey("DayPeriodId");

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId");

                    b.Navigation("DayPeriod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Preference", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Day", "Day")
                        .WithMany("Preferences")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.DayPeriod", "DayPeriod")
                        .WithMany("Preferences")
                        .HasForeignKey("DayPeriodId");

                    b.HasOne("Ezac.Roster.Domain.Entities.Job", "Job")
                        .WithMany("Preferences")
                        .HasForeignKey("JobId");

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("DayPeriod");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.ApplicationCalendar", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.Navigation("DayPeriods");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Preferences");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
