// <auto-generated />
using System;
using Ezac.Roster.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ezac.Roster.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240508070822_improve-dataseeding")]
    partial class improvedataseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.ApplicationCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Calendars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 11, 8, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8046),
                            Name = "Zweefvliegkalender",
                            Start = new DateTime(2024, 5, 8, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c661ff4c-d2fc-4311-a526-cc3e200ecbbc"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 7, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5c1be5ba-c4de-4abf-b9fa-48b71d324fdc"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 8, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("550eecf2-defb-4436-9c9b-0d6cb74a40d8"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 9, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Thursday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e8a9b655-8850-408e-9bb7-7da76e0a5438"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 10, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Friday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("52e1dc86-5f21-41b3-a79e-76d7c3a6e597"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 11, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Saturday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dec7804d-805f-4b5d-9b4e-ac5f1b5818ef"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 12, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Sunday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0fb48f62-0a8d-4847-a22d-8d7608fa35fd"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 13, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Monday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5823435f-8d3e-4c40-8b1d-d46e139d009c"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 14, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("35b619ee-73c9-4a26-86d7-b771be2cd94a"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 15, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7345eb45-aac9-4e2e-a02b-39974c4aa3f2"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 16, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Thursday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("139e538c-f54e-4ad2-9366-54f359a370b7"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 17, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Friday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("63ff453a-e093-488e-b36b-b7abbaff76f9"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 18, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Saturday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("40f19b92-5539-4cc4-b48a-471f34c403f4"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 19, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Sunday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7f8c7716-ac19-4c18-8bd9-72b2dea156e4"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 20, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Monday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("47c10a2b-7406-4f4c-8888-6fc9c98c214f"),
                            CalendarId = new Guid("d6cf6e97-b9cc-47a9-a7d4-2ec8219d2f35"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 21, 9, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("DayPeriods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00df25d8-b08a-4360-b9fe-8f3289e2d8ad"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c661ff4c-d2fc-4311-a526-cc3e200ecbbc"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 7, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 7, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3ba02c3a-20ce-436d-8f3b-5add4867d132"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c661ff4c-d2fc-4311-a526-cc3e200ecbbc"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 8, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 7, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2142c975-0200-4704-a6e0-5bb45ea9116d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c661ff4c-d2fc-4311-a526-cc3e200ecbbc"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 8, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 8, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("321458e3-93ad-45e2-bde3-4477b562f9b0"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5c1be5ba-c4de-4abf-b9fa-48b71d324fdc"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 8, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 8, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0c4be018-32f0-4871-95f6-2c1dd58c8671"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5c1be5ba-c4de-4abf-b9fa-48b71d324fdc"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 9, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 8, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("939f545b-fe6a-4864-9aec-b0e3d3cb7aa3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5c1be5ba-c4de-4abf-b9fa-48b71d324fdc"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 9, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 9, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bf5f978b-91c3-4aa4-a61d-cdf4e1bf2a69"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("550eecf2-defb-4436-9c9b-0d6cb74a40d8"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 9, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 9, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1e7ad8cf-b69b-4de3-9fbd-dcaa66c5e339"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("550eecf2-defb-4436-9c9b-0d6cb74a40d8"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 10, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 9, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fcc17d4b-6d6d-4794-996c-748b381861a0"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("550eecf2-defb-4436-9c9b-0d6cb74a40d8"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 10, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 10, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e9d19b60-6c61-4ea2-899d-bc575c264db8"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e8a9b655-8850-408e-9bb7-7da76e0a5438"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 10, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 10, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("57368fe1-2397-4091-8527-56652b9ecc45"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e8a9b655-8850-408e-9bb7-7da76e0a5438"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 11, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 10, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b4e03a98-4dc5-4bfd-935b-8d648f0bf5f9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e8a9b655-8850-408e-9bb7-7da76e0a5438"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 11, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 11, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0cffb1ab-e8f9-4d67-aab9-5e20c3078063"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("52e1dc86-5f21-41b3-a79e-76d7c3a6e597"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 11, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 11, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7f5e0d27-2466-4dc0-bae9-cb73218ad48b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("52e1dc86-5f21-41b3-a79e-76d7c3a6e597"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 12, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 11, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("28c44bd8-d0e7-47d0-9955-322f7a610bbc"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("52e1dc86-5f21-41b3-a79e-76d7c3a6e597"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 12, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 12, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("516066a7-99e3-4860-b9d2-31a28fccb367"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("dec7804d-805f-4b5d-9b4e-ac5f1b5818ef"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 12, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 12, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b239b036-fbdd-4488-b819-fae6cc0bfef2"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("dec7804d-805f-4b5d-9b4e-ac5f1b5818ef"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 13, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 12, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("19c97464-cdeb-4b01-8ab6-3311fa783d01"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("dec7804d-805f-4b5d-9b4e-ac5f1b5818ef"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 13, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 13, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("05cff88a-3706-4eb0-a119-0c11e501a4b0"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("0fb48f62-0a8d-4847-a22d-8d7608fa35fd"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 13, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 13, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e9c1d8c9-c0b8-4cc1-947a-081c15b481bf"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("0fb48f62-0a8d-4847-a22d-8d7608fa35fd"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 14, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 13, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("32dd3bc5-5ab1-4ecb-a53e-7d6969392f42"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("0fb48f62-0a8d-4847-a22d-8d7608fa35fd"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 14, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 14, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2add9afc-31ed-4353-98a1-02ebb272ae62"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5823435f-8d3e-4c40-8b1d-d46e139d009c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 14, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 14, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2cc8e078-b61a-4bea-89ab-050d2ab975a4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5823435f-8d3e-4c40-8b1d-d46e139d009c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 15, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 14, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e84d3bd0-89ed-4763-a7fc-63aab3b3a5b4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("5823435f-8d3e-4c40-8b1d-d46e139d009c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 15, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 15, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3e8b4c1b-e4df-4166-b8d3-b46bf95732fb"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("35b619ee-73c9-4a26-86d7-b771be2cd94a"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 15, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 15, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1f32a955-6420-45e7-ba51-7d3bfa0d68ef"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("35b619ee-73c9-4a26-86d7-b771be2cd94a"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 16, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 15, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("08602f88-3014-49d3-bf67-589fd2e2bdbe"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("35b619ee-73c9-4a26-86d7-b771be2cd94a"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 16, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 16, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d39fbb71-4db4-4478-a045-5b3bf95b505d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7345eb45-aac9-4e2e-a02b-39974c4aa3f2"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 16, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 16, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("746ba541-e497-4dc4-adac-6bdb6953cf48"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7345eb45-aac9-4e2e-a02b-39974c4aa3f2"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 17, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 16, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fcacfc1c-8a78-42ec-b938-26a19ecf6a69"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7345eb45-aac9-4e2e-a02b-39974c4aa3f2"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 17, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 17, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("49e47a61-b2e7-4421-aaf5-0c7e504ae81e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("139e538c-f54e-4ad2-9366-54f359a370b7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 17, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 17, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f9caee3e-f8df-41e8-a9ef-8946fceedbd0"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("139e538c-f54e-4ad2-9366-54f359a370b7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 18, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 17, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("11731e2a-ca97-4359-bbd5-055db8defe07"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("139e538c-f54e-4ad2-9366-54f359a370b7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 18, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 18, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a10bd8f9-7f18-4a5c-b15d-e413d60d3345"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("63ff453a-e093-488e-b36b-b7abbaff76f9"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 18, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 18, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("03b12810-4284-45a7-badf-ed17cb8cd138"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("63ff453a-e093-488e-b36b-b7abbaff76f9"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 19, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 18, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("df349e51-8ffd-4dae-bc19-4abac5f1213f"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("63ff453a-e093-488e-b36b-b7abbaff76f9"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 19, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 19, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7a9b3ad3-1b69-42b2-a1a9-16eea5453172"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("40f19b92-5539-4cc4-b48a-471f34c403f4"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 19, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 19, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4769e247-9d08-47c8-83f0-ed43efe7aac8"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("40f19b92-5539-4cc4-b48a-471f34c403f4"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 20, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 19, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ec652a3c-146d-4373-8fa6-8b5f52e65927"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("40f19b92-5539-4cc4-b48a-471f34c403f4"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 20, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 20, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f5450e99-66a9-42f6-ba01-fcd2e4fa8244"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7f8c7716-ac19-4c18-8bd9-72b2dea156e4"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 20, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 20, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("69cc80d0-b90b-4cc9-b591-e7cd494282a7"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7f8c7716-ac19-4c18-8bd9-72b2dea156e4"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 21, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 20, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f67c320e-0830-40df-831d-015ddb6bdc1d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("7f8c7716-ac19-4c18-8bd9-72b2dea156e4"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 21, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 21, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("50363011-f3b1-4d7c-9566-693ba7d334eb"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("47c10a2b-7406-4f4c-8888-6fc9c98c214f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 21, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 21, 17, 38, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("19e0042d-cce5-40b9-b67e-8cbcd0ac29d9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("47c10a2b-7406-4f4c-8888-6fc9c98c214f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 22, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 21, 22, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("05cda36f-ddf9-4dec-a88b-eebd5ca7f67a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("47c10a2b-7406-4f4c-8888-6fc9c98c214f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 22, 8, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 22, 2, 8, 22, 312, DateTimeKind.Local).AddTicks(8000),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DayPeriodId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lierist",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Startofficier",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bardienst",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Instructeur",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Preference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("DayPeriodId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Preference");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Scaling")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnny@ezac.com",
                            IsAdmin = false,
                            Name = "Johnny Debeer",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alfie@ezac.com",
                            IsAdmin = false,
                            Name = "Alfonso Rosseel",
                            Scaling = 0.5,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Admin@ezac.com",
                            IsAdmin = true,
                            Name = "Mohammed Ali",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PermissionUser", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("PermissionUser");

                    b.HasData(
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000003"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000004"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000001"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000003"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            PermissionsId = new Guid("00000000-0000-0000-0000-000000000004"),
                            UsersId = new Guid("00000000-0000-0000-0000-000000000007")
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.ApplicationCalendar", "Calendar")
                        .WithMany("Days")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Day", "Day")
                        .WithMany("DayPeriods")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.DayPeriod", "DayPeriod")
                        .WithMany("Jobs")
                        .HasForeignKey("DayPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.Permission", "Permission")
                        .WithMany("Jobs")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayPeriod");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Preference", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Day", "Day")
                        .WithMany("Preferences")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.DayPeriod", "DayPeriod")
                        .WithMany("Preferences")
                        .HasForeignKey("DayPeriodId");

                    b.HasOne("Ezac.Roster.Domain.Entities.Job", "Job")
                        .WithMany("Preferences")
                        .HasForeignKey("JobId");

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("DayPeriod");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermissionUser", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.ApplicationCalendar", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.Navigation("DayPeriods");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Permission", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
