// <auto-generated />
using System;
using Ezac.Roster.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ezac.Roster.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCalendarUser", b =>
                {
                    b.Property<Guid>("ApplicationCalendarsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationCalendarsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ApplicationCalendarUser");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.ApplicationCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Calendars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 11, 23, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6299),
                            Name = "Zweefvliegkalender",
                            Start = new DateTime(2024, 5, 23, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3e0de1b-da39-4e6c-97c0-8ddcb9c1907c"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 22, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e64d0e2b-827b-4132-87b0-f037001fb3b1"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 23, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Thursday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1105e5f1-a97f-48e5-8361-1c2365a2f401"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 24, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Friday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("17cdaf3f-b4df-4d56-bf18-88e6229bc182"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 25, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Saturday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d188ba08-1115-4a14-827b-9c16db474e61"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 26, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Sunday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a76173a5-6036-4e82-afeb-98f592123d17"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 27, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Monday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("725c1833-d906-47ec-90ef-6f313165822b"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 28, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6d326957-4b3a-4f15-bef0-6fd28d2a86f7"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 29, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("81b773a8-cdc6-48b9-8f49-403bd31f24e8"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 30, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Thursday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1112e994-bc14-44c1-a3f7-03d782fdac7c"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 5, 31, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Friday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("45521cdc-c0bd-46b6-a3fe-b5f18b126392"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 1, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Saturday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d9a80bd1-acfa-4fa4-ae9d-051a238a9d0d"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 2, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            Name = "Sunday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4b04072b-a5bf-4c62-a188-11204dade305"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 3, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Monday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e6149a16-876b-4fbb-8240-a20614c0fd1b"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 4, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Tuesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("34856a0b-550e-446c-b84b-758eda38795f"),
                            CalendarId = new Guid("ad26e9ce-add9-496a-90ec-1ba1d468af9e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2024, 6, 5, 10, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            Name = "Wednesday",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("DayPeriods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09311b49-09c2-4023-ac39-ee80a36d9b0c"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c3e0de1b-da39-4e6c-97c0-8ddcb9c1907c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 22, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 22, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ba1bd0b1-d71c-4885-9584-2685ed6928c6"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c3e0de1b-da39-4e6c-97c0-8ddcb9c1907c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 23, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 22, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("057a3e48-c02f-4330-b958-ca42c53e8846"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("c3e0de1b-da39-4e6c-97c0-8ddcb9c1907c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 23, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 23, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ff434436-d735-46b1-8dbb-89c7629a3409"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e64d0e2b-827b-4132-87b0-f037001fb3b1"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 23, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 23, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d7c721fd-46d0-4dea-b849-42132de95b59"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e64d0e2b-827b-4132-87b0-f037001fb3b1"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 24, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 23, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cc6f5be2-f992-4857-ba8c-0cd796366105"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e64d0e2b-827b-4132-87b0-f037001fb3b1"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 24, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 24, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("50e94c77-45d4-4a64-9783-397e0b24e4a2"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("1105e5f1-a97f-48e5-8361-1c2365a2f401"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 24, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 24, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d19a8cce-4411-416e-a0ec-6910ea1f808a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("1105e5f1-a97f-48e5-8361-1c2365a2f401"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 25, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 24, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8852116a-a109-4fd4-ad12-135ec7e29fde"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("1105e5f1-a97f-48e5-8361-1c2365a2f401"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 25, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 25, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0537291d-104b-4ccb-a2f2-c2ab15301a80"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("17cdaf3f-b4df-4d56-bf18-88e6229bc182"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 25, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 25, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1aa389b0-d5ec-4407-be12-73d5c4c87d6b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("17cdaf3f-b4df-4d56-bf18-88e6229bc182"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 26, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 25, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2bec6715-d360-4b46-bfdf-d1c0fbbded8e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("17cdaf3f-b4df-4d56-bf18-88e6229bc182"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 26, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 26, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8b136fc8-f3e1-4f2d-a409-399c988e738c"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d188ba08-1115-4a14-827b-9c16db474e61"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 26, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 26, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0fe1a063-4f03-4a72-aa2b-e6ed93e7c187"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d188ba08-1115-4a14-827b-9c16db474e61"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 27, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 26, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1f45a97c-429b-445c-a07c-78257cd03fd4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d188ba08-1115-4a14-827b-9c16db474e61"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 27, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 27, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fddcc3e4-490c-43c9-a4bf-ae7aee545702"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("a76173a5-6036-4e82-afeb-98f592123d17"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 27, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 27, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6b69543c-d313-468f-9f68-b80e794ad385"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("a76173a5-6036-4e82-afeb-98f592123d17"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 28, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 27, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1ad5a59e-c16c-4a75-a117-19da3729c71b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("a76173a5-6036-4e82-afeb-98f592123d17"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 28, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 28, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("81886b28-badb-418c-bd6e-736cd72ef28f"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("725c1833-d906-47ec-90ef-6f313165822b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 28, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 28, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a9dddd0d-3006-4350-8731-855aeb88292d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("725c1833-d906-47ec-90ef-6f313165822b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 29, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 28, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b28f34dc-c566-4232-98f4-60fe521ea4dd"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("725c1833-d906-47ec-90ef-6f313165822b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 29, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 29, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0f901e2b-69c2-4884-a3b6-bd24155f6466"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("6d326957-4b3a-4f15-bef0-6fd28d2a86f7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 29, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 29, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a0518765-02b0-45aa-9b23-398863591c8d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("6d326957-4b3a-4f15-bef0-6fd28d2a86f7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 30, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 29, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("63a17f3c-0f60-45ac-bfa9-a913498a0d93"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("6d326957-4b3a-4f15-bef0-6fd28d2a86f7"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 30, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 30, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("04a9be5d-02e8-421d-a996-f2ff6fa541a4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("81b773a8-cdc6-48b9-8f49-403bd31f24e8"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 30, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 30, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("397aaec1-11aa-4089-b49d-d5f2e235e2ae"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("81b773a8-cdc6-48b9-8f49-403bd31f24e8"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 31, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 30, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3742d091-ea0a-4f7f-82f4-9f5357b9792d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("81b773a8-cdc6-48b9-8f49-403bd31f24e8"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 31, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 5, 31, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("88f5bb43-3e88-498e-90d3-c7bdd00b0ae4"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("1112e994-bc14-44c1-a3f7-03d782fdac7c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 5, 31, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 5, 31, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7a5f6b8c-0be1-4512-9491-8edd38f62870"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("1112e994-bc14-44c1-a3f7-03d782fdac7c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 1, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 5, 31, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("363d7214-2f2f-492a-9293-20a4c6b18839"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("1112e994-bc14-44c1-a3f7-03d782fdac7c"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 1, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 1, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c1e89a40-be26-48a9-98da-bfc6993504ba"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("45521cdc-c0bd-46b6-a3fe-b5f18b126392"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 1, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 1, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("53d70b98-7e91-45cb-b863-17c4aafa26b2"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("45521cdc-c0bd-46b6-a3fe-b5f18b126392"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 2, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 1, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("510ec51f-ba28-40c3-b76d-8fc2906b34c7"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("45521cdc-c0bd-46b6-a3fe-b5f18b126392"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 2, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 2, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0d5e37f7-d8c6-4969-b7c9-0f16ec7884b9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d9a80bd1-acfa-4fa4-ae9d-051a238a9d0d"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 2, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 2, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9c882991-f6ff-447c-9aef-3f6d8b211256"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d9a80bd1-acfa-4fa4-ae9d-051a238a9d0d"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 3, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 2, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c2387ed5-a9c7-4066-bce3-b286bbcaccd7"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("d9a80bd1-acfa-4fa4-ae9d-051a238a9d0d"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 3, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 3, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0f49cdf0-0300-4ad9-9102-f3e2b13b71f3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("4b04072b-a5bf-4c62-a188-11204dade305"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 3, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 3, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9cec4d56-c95a-4de7-a28b-3962415cdcc3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("4b04072b-a5bf-4c62-a188-11204dade305"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 4, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 3, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4b445e34-835a-423f-990d-5598ea2615c3"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("4b04072b-a5bf-4c62-a188-11204dade305"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 4, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 4, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1945cafd-2b79-4a55-9e30-50fedc455667"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e6149a16-876b-4fbb-8240-a20614c0fd1b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 4, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 4, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f5e06c5c-b5b1-433b-acde-ccf2b72de4ec"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e6149a16-876b-4fbb-8240-a20614c0fd1b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 5, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 4, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("282e8cc3-2a6a-493c-86ac-502978217453"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("e6149a16-876b-4fbb-8240-a20614c0fd1b"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 5, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 5, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3df6a870-877b-4559-9d0c-4c05089bc759"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("34856a0b-550e-446c-b84b-758eda38795f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 5, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "A",
                            Start = new DateTime(2024, 6, 5, 18, 31, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7e40236f-f5f9-4c99-8fa6-51aa3131d10a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("34856a0b-550e-446c-b84b-758eda38795f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 6, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "B",
                            Start = new DateTime(2024, 6, 5, 23, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("481a927d-66b4-42d4-abb8-038816dc8a6b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = new Guid("34856a0b-550e-446c-b84b-758eda38795f"),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2024, 6, 6, 9, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            IsOpen = true,
                            Name = "C",
                            Start = new DateTime(2024, 6, 6, 3, 1, 16, 377, DateTimeKind.Local).AddTicks(6252),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DayPeriodId");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lierist",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Startofficier",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bardienst",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Instructeur",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Preference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DayPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("DayPeriodId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Preference");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Scaling")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnny@ezac.com",
                            IsAdmin = false,
                            Name = "Johnny Debeer",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alfie@ezac.com",
                            IsAdmin = false,
                            Name = "Alfonso Rosseel",
                            Scaling = 0.5,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Admin@ezac.com",
                            IsAdmin = true,
                            Name = "Mohammed Ali",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Diego@ezac.com",
                            IsAdmin = false,
                            Name = "Diego Maradonna",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mitch@ezac.com",
                            IsAdmin = false,
                            Name = "Mitch Mitchell",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mileto@ezac.com",
                            IsAdmin = false,
                            Name = "Mileto Di Marco",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Antoinne@ezac.com",
                            IsAdmin = true,
                            Name = "Antoinne De Vlieger",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Siegfried@ezac.com",
                            IsAdmin = true,
                            Name = "Siegfried Dedeyne",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Dries@ezac.com",
                            IsAdmin = false,
                            Name = "Dries Deboosere",
                            Scaling = 1.0,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("48b9f3ba-3e29-4252-a7e8-e3a5230d6d2a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 1,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("8f5ffe5f-6e5b-4479-9c82-87df97d47909"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 5,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20b36ec9-b397-40fc-8242-b1159f47cf1e"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("24fe07a3-4476-411f-a42e-e8f72abe1c2c"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 6,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("5caace7f-d657-4977-8882-794c7f71a772"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 8,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("73ccb532-a2c5-49c0-bc7b-b0e7058e8cb7"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 2,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("054c4690-7296-4e8c-aa5f-c2d0a54ce4c6"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 1,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("ec1c1d5b-28e7-45b0-bef3-9677f6f4044c"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 9,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("d6cf5637-befe-496a-8ec9-fc3c86d04ab9"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 7,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("6f34e23e-a1b4-4fb8-98a9-968b183b9a3b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("0fbb30a8-e0ee-4454-875d-da20bf9af0c2"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 3,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("0aaf5d73-1a04-4dee-a5fd-9a19396c309d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 1,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("86d97cd1-1589-4024-a3e2-3f2469c5ed66"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 5,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("58a4d20e-d04c-4790-8cfb-bda660e6cb94"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("6063389f-ad59-4009-b65d-92687b974194"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 7,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("346f591f-5e6f-40c5-b05a-0d54c7064068"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 2,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = new Guid("e4abd73d-74be-4a1f-b458-1a8caf125163"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 3,
                            Name = "Lierist",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("dd56b9c4-b7d2-4c7a-ad1e-10d6ab47cb6d"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 8,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("6929bfb2-f14d-4ac5-bced-ae6a5cb121c0"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 9,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = new Guid("0d614945-cc8d-4fd3-b9c8-2d9a65a3c44b"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 4,
                            Name = "Startofficier",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("b75af589-1934-49a1-b8a0-02c557a04a4a"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 2,
                            Name = "Bardienst",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = new Guid("b709e7c7-0e4d-4c83-8589-6073149223be"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 8,
                            Name = "Instructeur",
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("00000000-0000-0000-0000-000000000013")
                        });
                });

            modelBuilder.Entity("ApplicationCalendarUser", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.ApplicationCalendar", null)
                        .WithMany()
                        .HasForeignKey("ApplicationCalendarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.ApplicationCalendar", "Calendar")
                        .WithMany("Days")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Day", "Day")
                        .WithMany("DayPeriods")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.DayPeriod", "DayPeriod")
                        .WithMany("Jobs")
                        .HasForeignKey("DayPeriodId");

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId");

                    b.Navigation("DayPeriod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Preference", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Day", "Day")
                        .WithMany("Preferences")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.DayPeriod", "DayPeriod")
                        .WithMany("Preferences")
                        .HasForeignKey("DayPeriodId");

                    b.HasOne("Ezac.Roster.Domain.Entities.Job", "Job")
                        .WithMany("Preferences")
                        .HasForeignKey("JobId");

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("DayPeriod");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("Ezac.Roster.Domain.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ezac.Roster.Domain.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.ApplicationCalendar", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Day", b =>
                {
                    b.Navigation("DayPeriods");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.DayPeriod", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Job", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Ezac.Roster.Domain.Entities.User", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Preferences");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
